a = "------Parth------- ALPHA sdfksds"
print(a.upper())
print(len(a))
print(a.lower())
print(a.rstrip("-"))
print(a.replace("Parth","PPARTHHHH"))
print(a.split(" "))
print(a.capitalize())
print(a.center(100))
print(a.count("A"))
print(a.endswith("s"))
print(a.find("P"))
print(a.isalnum())
print(a.isalpha())
print(a.islower())
print(a.isprintable())
print(a.istitle())
print(a.isspace())
print(a.isupper())